# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: 'Terminal 1'
    openMode: split-left
    init: npm install # runs during prebuild
    command: npm start
  - name: 'Terminal 2'
    openMode: split-right
    init: chmod 0755 ./chrome-test-setup.sh # runs during prebuild
    command: sh ./chrome-test-setup.sh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview
    visibility: public
  - port: 9915
    visibility: public
